services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netlogix\Nxsimplecdn\:
    resource: '../Classes/*'

  Netlogix\Nxsimplecdn\SystemResource\CdnSystemResourcePublisher:
    decorates: TYPO3\CMS\Core\SystemResource\Publishing\SystemResourcePublisherInterface
    arguments:
      $innerPublisher: '@.inner'
