services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netlogix\Nxsimplecdn\:
    resource: '../Classes/*'

  Netlogix\Nxsimplecdn\Xclass\PageRenderer:
    arguments:
      $assetsCache: '@cache.assets'
